---
title: "GSEA by patient"
author: "Hongke Peng"
date: '2022-08-11'
output: html_document
---

#load library
```{r}
library(Seurat)
library(Scillus)
library(progeny)
library(dplyr)
library(tidyr)
library(tibble)
library(dittoSeq)
library(clusterProfiler)
library(gprofiler2)
library(enrichplot)
library(escape)
library(msigdbr)
library(GSEABase)
library(GSVA)
library(org.Hs.eg.db)
```

```{r,fig.width=6,fig.height=5}
srt <- readRDS("composition_combine_srt_figure/refined_srt.rds")
dittoDimPlot(srt, var = "refined.cluster", reduction.use = "mnnUMAP", color.panel = dittoColors(), do.raster = T, size = 0.1, do.label = T, labels.size = 3)
```
#make group
```{r,fig.width=5.5, fig.height=5}
x <- subset(srt, refined.cluster %in% 1:6 & patient != "CLL427")
x$stage <- "TN"
x$stage[x$patient %in% c("CLL281", "CLL295")] <- "VEN"
x$stage[x$patient %in% c("CLL400", "CLL427")] <- "Chemo"

x$category <- paste(x$compartment, x$patient, x$stage, sep = "_")

table(x$compartment)
table(x$patient)
table(x$stage)
table(x$category)
dittoDimPlot(x, var = "refined.cluster", reduction.use = "mnnUMAP", color.panel = dittoColors(), do.raster = T, size = 0.1, do.label = T, labels.size = 3)
```

#uncorr cluster
##don't rm IG genes
```{r, fig.width=16, fig.height=5}
#normalization
x <- NormalizeData(x)
x <- FindVariableFeatures(x)
VlnPlot(x, group.by = "patient", features = c("nCount_RNA", "nFeature_RNA","subsets_Mito_percent","S.Score", "G2M.Score"), pt.size = 0, ncol = 3)
x <- ScaleData(x, vars.to.regress = c("nCount_RNA", "nFeature_RNA","subsets_Mito_percent"))
hvg <- VariableFeatures(x)
#igh <- hvg[grep("^IGH", hvg)]
#igl <- hvg[grep("^IGL", hvg)]
#igk <- hvg[grep("^IGK", hvg)]

#bcr <- c(igh, igl, igk)
#hvg <- hvg[!(hvg %in% bcr)]

x <- RunPCA(x, reduction.name = "uncorrPCA", features = hvg)
ElbowPlot(x, reduction = "uncorrPCA", ndims = 50)
#run UMAP
dims.to.use <- 20
x <- RunUMAP(x, reduction = "uncorrPCA", dims = 1:dims.to.use, reduction.name = "uncorrUMAP", reduction.key = "uncorrUMAP_")
#visualization
p1 <- dittoDimPlot(x, var = "source", reduction.use = "uncorrUMAP", color.panel = dittoColors()[1:2], do.raster = T, size = 0.01)
p2 <- dittoDimPlot(x, var = "compartment", reduction.use = "uncorrUMAP", color.panel = dittoColors()[3:4], do.raster = T, size = 0.01)
p3 <- dittoDimPlot(x, var = "patient", reduction.use = "uncorrUMAP", color.panel = dittoColors()[4:12], do.raster = T, size = 0.01)
p <- p1 + p2 + p3
p
```

```{r}
table(x$patient)
table(x$compartment)
table(x$patient, x$compartment)
```

#by patient analysis
```{r}
#load GMT
biocata <- read.gmt("/stornext/Genomics/data/CLL_venetoclax/workspace/PB_LN_comparison/GeneSet/c2.cp.biocarta.v7.5.1.entrez.gmt.txt")
pid <- read.gmt("/stornext/Genomics/data/CLL_venetoclax/workspace/PB_LN_comparison/GeneSet/c2.cp.pid.v7.5.1.entrez.gmt.txt")
go.bp <- read.gmt("/stornext/Genomics/data/CLL_venetoclax/workspace/T_under_VEN/Aim2/analysis/pathway/c5.go.bp.v7.4.entrez.gmt")
h <- read.gmt("/stornext/Genomics/data/CLL_venetoclax/workspace/PB_LN_comparison/GeneSet/h.all.v7.5.1.entrez.gmt.txt")

gmt <- rbind(biocata, pid, go.bp, h)


#prepare gene set collection ----
all_gene_set <- data.frame()
##C2 canonical pathway
for (i in c("CP:BIOCARTA", "CP:KEGG", "CP:REACTOME", "CP:WIKIPATHWAYS", "CP:PID")) {
  mtx <- msigdbr(species = "Homo sapiens",category = "C2",subcategory = i)
  mtx <- as.data.frame(mtx)
  all_gene_set <- rbind(all_gene_set, mtx)
}
##go BP
mtx <- msigdbr(species = "Homo sapiens",category = "C5",subcategory = "GO:BP")
mtx <- as.data.frame(mtx)
all_gene_set <- rbind(all_gene_set, mtx)
##Hallmark
mtx <- msigdbr(species = "Homo sapiens",category = "H")
mtx <- as.data.frame(mtx)
all_gene_set <- rbind(all_gene_set, mtx)

gs=split(all_gene_set$gene_symbol,all_gene_set$gs_name)
gs=lapply(gs,unique) # 10661 gene sets

gs <- gs[names(gs)[lengths(gs) <= 1500]]

length(unique(unlist(gs))) #18707
sum(unique(unlist(gs)) %in% rownames(x)) #16481

min_num <- c()
cover.ls <- c()
length.ls <- lengths(gs)

for (i in 1:length(gs)) {
  min_num[i] <- sum(gs[[i]] %in% rownames(x))
  cover.ls[i] <- sum(gs[[i]] %in% rownames(x))/length.ls[i]
}

df <- data.frame(fraction = cover.ls)
ggplot(df, aes(x = fraction)) + geom_histogram(bins = 100) 
gs <- gs[min_num >= 10 & cover.ls > 0.9]

gmt <- data.frame(term = all_gene_set$gs_name, 
                  gene = all_gene_set$entrez_gene)
gmt <- gmt[gmt$term %in% names(gs), ]

deg.ls <- list()
#I already save deg
for (i in unique(x$patient)) {
  deg.ls[[i]] <- read.csv(paste0("gsea_by_patient_figure/", i, "_deg.csv"), row.names = 1)
}

gsea.ls <- list()
for (i in unique(x$patient)) {
  #y <- subset(x, patient == i)
  #DefaultAssay(y) <- "RNA"
  #y <- NormalizeData(y)
  #y <- FindVariableFeatures(y)
  #y <- ScaleData(y)
  #deg <- FindMarkers(y, group.by = "compartment", ident.1 = "LN", ident.2 = "PB", assay = "RNA", logfc.threshold = 0, min.pct = 0, test.use = "MAST")
  #write.csv(deg, paste0("gsea_by_patient_figure/", i, "_deg.csv"))
  #deg.ls[[i]] <- deg
  
  #df <- deg
  df <- deg.ls[[i]]
  #df <- df[df$p_val_adj < 0.01, ]
  df <- df[df$pct.1 > 0.05 | df$pct.2 > 0.05, ]
  df$gene=rownames(df)
  #rm genes with small faction of cells expressing it
  id=bitr(df$gene,"SYMBOL","ENTREZID","org.Hs.eg.db") #5.38% of input gene IDs are fail to map...
  #make geneList
  marker=merge(df,id,by.x="gene",by.y="SYMBOL")
  marker=data.frame(logFC=marker$avg_log2FC,SYMBOL=marker$ENTREZID)
  geneList=marker$logFC
  names(geneList)=marker$SYMBOL
  geneList=sort(geneList,decreasing=T)

  gsea.result <- GSEA(geneList, TERM2GENE = gmt, seed = T, pvalueCutoff = 0.05, pAdjustMethod = "BH")
  #write.csv(gsea.result@result, paste0("gsea_by_patient_figure/", i, "_gsea.csv"))
  gsea.ls[[i]] <- gsea.result@result
}
```

```{r}
ID <- c("HALLMARK_MYC_TARGETS_V1", "HALLMARK_MYC_TARGETS_V2", "HALLMARK_E2F_TARGETS", "HALLMARK_G2M_CHECKPOINT", "HALLMARK_TNFA_SIGNALING_VIA_NFKB", "HALLMARK_INTERFERON_ALPHA_RESPONSE", "HALLMARK_INTERFERON_GAMMA_RESPONSE", "HALLMARK_KRAS_SIGNALING_DN", "HALLMARK_MTORC1_SIGNALING", "HALLMARK_OXIDATIVE_PHOSPHORYLATION", "HALLMARK_GLYCOLYSIS", "HALLMARK_HEME_METABOLISM", "HALLMARK_HYPOXIA", 
             "GOBP_INTERLEUKIN_4_PRODUCTION", "REACTOME_CYTOKINE_SIGNALING_IN_IMMUNE_SYSTEM", "GOBP_RESPONSE_TO_CYTOKINE", "GOBP_POSITIVE_REGULATION_OF_CYTOKINE_PRODUCTION", "GOBP_CYTOKINE_MEDIATED_SIGNALING_PATHWAY", "GOBP_INTERLEUKIN_12_PRODUCTION", "GOBP_POSITIVE_REGULATION_OF_INTERLEUKIN_12_PRODUCTION",
             "PID_BCR_5PATHWAY", "REACTOME_SIGNALING_BY_THE_B_CELL_RECEPTOR_BCR", "REACTOME_SIGNALING_BY_THE_B_CELL_RECEPTOR_BCR", "REACTOME_CROSS_PRESENTATION_OF_SOLUBLE_EXOGENOUS_ANTIGENS_ENDOSOMES", 
              "GOBP_B_CELL_ACTIVATION", "GOBP_B_CELL_MEDIATED_IMMUNITY", "GOBP_REGULATION_OF_B_CELL_DIFFERENTIATION", "BIOCARTA_41BB_PATHWAY", "WP_ATM_SIGNALING_PATHWAY"
)

ID <- c("HALLMARK_MYC_TARGETS_V2", "HALLMARK_MYC_TARGETS_V1", "HALLMARK_G2M_CHECKPOINT", "HALLMARK_INTERFERON_ALPHA_RESPONSE", 
        "HALLMARK_OXIDATIVE_PHOSPHORYLATION", "HALLMARK_INTERFERON_GAMMA_RESPONSE", "HALLMARK_INFLAMMATORY_RESPONSE",
        "HALLMARK_GLYCOLYSIS", "HALLMARK_PI3K_AKT_MTOR_SIGNALING", "HALLMARK_P53_PATHWAY", "HALLMARK_TGF_BETA_SIGNALING", 
        "HALLMARK_IL6_JAK_STAT3_SIGNALING", "HALLMARK_TNFA_SIGNALING_VIA_NFKB", "HALLMARK_IL2_STAT5_SIGNALING", # HallMark
        
        "PID_MYC_ACTIV_PATHWAY", "PID_BCR_5PATHWAY", "PID_TELOMERASE_PATHWAY", "PID_IL2_PI3K_PATHWAY", "PID_IL12_2PATHWAY",
        "PID_IL4_2PATHWAY", "PID_AR_PATHWAY", "PID_ERA_GENOMIC_PATHWAY", "PID_BARD1_PATHWAY", "PID_CD40_PATHWAY", #PID
        
        "BIOCARTA_PROTEASOME_PATHWAY", "BIOCARTA_P53HYPOXIA_PATHWAY", "BIOCARTA_CTLA4_PATHWAY", "BIOCARTA_CCR5_PATHWAY", 
        "BIOCARTA_IL2_PATHWAY", "BIOCARTA_ATM_PATHWAY", "BIOCARTA_CSK_PATHWAY", #BIOCARTA
        
        "KEGG_ANTIGEN_PROCESSING_AND_PRESENTATION", "KEGG_B_CELL_RECEPTOR_SIGNALING_PATHWAY",  #KEGG
        
        "REACTOME_MRNA_SPLICING_MINOR_PATHWAY", "REACTOME_INTERFERON_ALPHA_BETA_SIGNALING", "REACTOME_MAPK6_MAPK4_SIGNALING",
        "ANTIGEN_PROCESSING_CROSS_PRESENTATION", "REACTOME_PD_1_SIGNALING", "REACTOME_INTERLEUKIN_21_SIGNALING", #REACTOME
        
        "GOBP_LEUKOCYTE_PROLIFERATION", "GOBP_B_CELL_DIFFERENTIATION", "GOBP_POSITIVE_REGULATION_OF_RESPONSE_TO_BIOTIC_STIMULUS",
        "GOBP_POSITIVE_REGULATION_OF_CYTOKINE_PRODUCTION", "GOBP_B_CELL_ACTIVATION_INVOLVED_IN_IMMUNE_RESPONSE", 
        "GOBP_POSITIVE_REGULATION_OF_CELL_CELL_ADHESION", "GOBP_RESPONSE_TO_INTERLEUKIN_4", "GOBP_INTERLEUKIN_12_PRODUCTION" #GOBP
        )

ID <- unique(ID)
ID <- factor(ID, levels = ID)

pathway.df <- data.frame()
for (i in names(gsea.ls)) {
  df <- gsea.ls[[i]]
  id.exist <- ID[(ID %in% df$ID)]
  df <- df[df$ID %in% id.exist, ]
  df$patient <- i
  pathway.df <- rbind(pathway.df, df)
}

pathway.df <- pathway.df[pathway.df$qvalue <= 0.05 & pathway.df$NES > 0, ]
pathway.df <- pathway.df[, c("ID", "Description", "NES", "qvalue", "patient")]
```

```{r,fig.width=7,fig.height=6}
ggplot(pathway.df, aes(x = patient, y = Description)) + 
  geom_point(aes(size = NES, colour = qvalue)) + 
  theme_bw() +
  theme(panel.grid = element_blank(),
        axis.text.x=element_text(angle=90,hjust = 1,vjust=0.5),
        axis.text.y=element_text(face = "bold", color = "grey40")) +
  scale_color_gradient(low="#35A355",high="#F3F8B2") + 
  #scale_fill_continuous() + 
  scale_y_discrete(position = "right") +
  labs(x=NULL,y=NULL) + 
  ggtitle("GSEA analysis for each patient")
#ggsave("gsea_by_patient_figure/gsea_term_by_patient.pdf", width = 6, height = 6)
```

```{r, fig.width=15, fig.height=10}
all_gsea_result <- gsea.ls$CLL400
all_gsea_result <- all_gsea_result[all_gsea_result$qvalue <= 0.01 & all_gsea_result$NES > 0, ]
colnames(all_gsea_result)[2:ncol(all_gsea_result)] <- paste0("CLL400.", colnames(all_gsea_result)[2:ncol(all_gsea_result)])
for (i in c("CLL281", "CLL295", "CLLc03", "CLLc11", "CLLc24", "CLLc33", "CLLc44")) {
  df_to_merge <- gsea.ls[[i]]
  df_to_merge <- df_to_merge[df_to_merge$qvalue <= 0.01 & df_to_merge$NES > 0, ]
  colnames(df_to_merge)[2:ncol(df_to_merge)] <- paste0(i, ".", colnames(df_to_merge)[2:ncol(df_to_merge)])
  all_gsea_result <- merge(all_gsea_result, df_to_merge, by = "ID", all = T)
}

all_gsea_result <- all_gsea_result[, c("ID", colnames(all_gsea_result)[grep(".NES$", colnames(all_gsea_result))])]
all_gsea_result[is.na(all_gsea_result)] <- 0
rownames(all_gsea_result) <- all_gsea_result$ID
all_gsea_result$ID <- NULL
pheatmap::pheatmap(all_gsea_result)
```



## GSEA by clusterprofiler
```{r,fig.width=5,fig.height=3}
up.ls <- list()
dw.ls <- list()
for (i in unique(x$patient)) {
  df <- read.csv(paste0("gsea_by_patient_figure/", i, "_deg.csv"), row.names = 1)
  df$logp <- -log(df$p_val_adj)
  ggplot(df, aes(x = avg_log2FC, y = logp)) + geom_point()
  df$gene=rownames(df)
  up <- df[df$avg_log2FC > 0.25 & df$logp > 100, ]
  up.ls[[i]] <- enrichGO(gene = up$gene, 
                         OrgDb = org.Hs.eg.db, 
                         keyType = "SYMBOL",
                         ont = "BP", 
                         pAdjustMethod = "BH",
                         pvalueCutoff  = 0.05,
                         qvalueCutoff  = 0.05,
                         readable = TRUE)
  
  dw <- df[df$avg_log2FC < -0.25 & df$logp > 100, ]
  dw.ls[[i]] <- enrichGO(gene = dw$gene, 
                         OrgDb = org.Hs.eg.db, 
                         keyType = "SYMBOL",
                         ont = "BP", 
                         pAdjustMethod = "BH",
                         pvalueCutoff  = 0.05,
                         qvalueCutoff  = 0.05,
                         readable = TRUE)
}
```

```{r,fig.width=7.5,fig.height=9}
up.ls <- list()
dw.ls <- list()
for (i in unique(x$patient)) {
  df <- read.csv(paste0("gsea_by_patient_figure/", i, "_deg.csv"), row.names = 1)
  df$logp <- -log(df$p_val_adj)
  ggplot(df, aes(x = avg_log2FC, y = logp)) + geom_point()
  df$gene=rownames(df)
  up <- df[df$avg_log2FC > 0.2 & df$p_val_adj < 0.01, ]
  id=bitr(up$gene,"SYMBOL","ENTREZID","org.Hs.eg.db")
  marker = merge(up, id, by.x = "gene", by.y = "SYMBOL")
  up <- enricher(gene = marker$ENTREZID, pvalueCutoff = 0.05, TERM2GENE = gmt)
  up.ls[[i]] <- up@result
  
  dw <- df[df$avg_log2FC < -0.2 & df$p_val_adj < 0.01, ]
  id=bitr(dw$gene,"SYMBOL","ENTREZID","org.Hs.eg.db")
  marker = merge(dw, id, by.x = "gene", by.y = "SYMBOL")
  dw <- enricher(gene = marker$ENTREZID, pvalueCutoff = 0.05, TERM2GENE = gmt)
  dw.ls[[i]] <- dw@result
}

#rm the terms that exist in both up and dw
up.f.ls <- list()
dw.f.ls <- list()
for (i in names(up.ls)) {
  up <- up.ls[[i]]
  up <- up[up$qvalue < 0.05, ]
  dw <- dw.ls[[i]]
  dw <- dw[dw$qvalue < 0.05, ]
  
  rm.ID <- intersect(up$ID, dw$ID)
  print(paste(i, "==============================================="))
  print(rm.ID)
  up <- up[!(up$ID %in% rm.ID), ]
  dw <- dw[!(dw$ID %in% rm.ID), ]
  up.f.ls[[i]] <- up
  dw.f.ls[[i]] <- dw
}
#find the common pathway shared by all patients
go.term <- unique(c(up.f.ls$CLL400$ID, up.f.ls$CLL281$ID, up.f.ls$CLL295$ID, up.f.ls$CLLc03$ID, up.f.ls$CLLc11$ID,up.f.ls$CLLc24$ID, up.f.ls$CLLc33$ID, up.f.ls$CLLc44$ID))
long.df <- c(up.f.ls$CLL400$ID, up.f.ls$CLL281$ID, up.f.ls$CLL295$ID, up.f.ls$CLLc03$ID, up.f.ls$CLLc11$ID,up.f.ls$CLLc24$ID, up.f.ls$CLLc33$ID, up.f.ls$CLLc44$ID)
common.use <- c()
for (i in 1:length(go.term)) {
  common.use[i] <- sum(long.df == go.term[i])
}
common.df <- data.frame(term = go.term, 
                        shared_by = common.use)

#find the common pathway shared by 5 treatment-naive patients
go.term <- unique(c(up.f.ls$CLLc03$ID, up.f.ls$CLLc11$ID, up.f.ls$CLLc24$ID, up.f.ls$CLLc33$ID, up.f.ls$CLLc44$ID))
long.df <- c(up.f.ls$CLLc03$ID, up.f.ls$CLLc11$ID, up.f.ls$CLLc24$ID, up.f.ls$CLLc33$ID, up.f.ls$CLLc44$ID)
common.use <- c()
for (i in 1:length(go.term)) {
  common.use[i] <- sum(long.df == go.term[i])
}
common.df.naive <- data.frame(term = go.term, 
                        shared_by = common.use)

#select ID I want to plot
ID <- c("HALLMARK_MYC_TARGETS_V2", "HALLMARK_MYC_TARGETS_V1", "HALLMARK_G2M_CHECKPOINT", "HALLMARK_INTERFERON_ALPHA_RESPONSE", 
        "HALLMARK_OXIDATIVE_PHOSPHORYLATION", "HALLMARK_INTERFERON_GAMMA_RESPONSE", "HALLMARK_INFLAMMATORY_RESPONSE",
        "HALLMARK_GLYCOLYSIS", "HALLMARK_PI3K_AKT_MTOR_SIGNALING", "HALLMARK_P53_PATHWAY", "HALLMARK_TGF_BETA_SIGNALING", 
        "HALLMARK_IL6_JAK_STAT3_SIGNALING", "HALLMARK_TNFA_SIGNALING_VIA_NFKB", "HALLMARK_IL2_STAT5_SIGNALING", # HallMark
        
        "PID_MYC_ACTIV_PATHWAY", "PID_BCR_5PATHWAY", "PID_TELOMERASE_PATHWAY", "PID_IL2_PI3K_PATHWAY", "PID_IL12_2PATHWAY",
        "PID_IL4_2PATHWAY", "PID_AR_PATHWAY", "PID_ERA_GENOMIC_PATHWAY", "PID_BARD1_PATHWAY", "PID_CD40_PATHWAY", #PID
        
        "BIOCARTA_PROTEASOME_PATHWAY", "BIOCARTA_P53HYPOXIA_PATHWAY", "BIOCARTA_CTLA4_PATHWAY", "BIOCARTA_CCR5_PATHWAY", 
        "BIOCARTA_IL2_PATHWAY", "BIOCARTA_ATM_PATHWAY", "BIOCARTA_CSK_PATHWAY", #BIOCARTA
        
        "KEGG_ANTIGEN_PROCESSING_AND_PRESENTATION", "KEGG_B_CELL_RECEPTOR_SIGNALING_PATHWAY",  #KEGG
        
        "REACTOME_MRNA_SPLICING_MINOR_PATHWAY", "REACTOME_INTERFERON_ALPHA_BETA_SIGNALING", "REACTOME_MAPK6_MAPK4_SIGNALING",
        "ANTIGEN_PROCESSING_CROSS_PRESENTATION", "REACTOME_PD_1_SIGNALING", "REACTOME_INTERLEUKIN_21_SIGNALING", #REACTOME
        
        "GOBP_LEUKOCYTE_PROLIFERATION", "GOBP_B_CELL_DIFFERENTIATION", "GOBP_POSITIVE_REGULATION_OF_RESPONSE_TO_BIOTIC_STIMULUS",
        "GOBP_POSITIVE_REGULATION_OF_CYTOKINE_PRODUCTION", "GOBP_B_CELL_ACTIVATION_INVOLVED_IN_IMMUNE_RESPONSE", 
        "GOBP_POSITIVE_REGULATION_OF_CELL_CELL_ADHESION", "GOBP_RESPONSE_TO_INTERLEUKIN_4", "GOBP_INTERLEUKIN_12_PRODUCTION" #GOBP
        )
ID <- factor(ID, levels = ID)
pathway.df <- data.frame()
for (i in names(up.f.ls)) {
  df <- up.f.ls[[i]]
  id.exist <- ID[(ID %in% df$ID)]
  df <- df[df$ID %in% id.exist, ]
  df$patient <- i
  pathway.df <- rbind(pathway.df, df)
}

pathway.df <- pathway.df[pathway.df$qvalue <= 0.05, c("ID", "Description", "GeneRatio","Count", "qvalue", "patient")]

pathway.df$log_qvalue <- - log(pathway.df$qvalue)
pathway.df$scaled_log_qvalue <- scale(pathway.df$log_qvalue, center = F)
pathway.df$scaled_log_qvalue[pathway.df$scaled_log_qvalue > 2.5] = 2.5
pathway.df$scaled_count <- scale(pathway.df$Count, center = F)

ggplot(pathway.df, aes(x = patient, y = Description)) + 
  geom_point(aes(size = Count, color = scaled_log_qvalue)) + 
  theme_bw() +
  theme(panel.grid = element_blank(),
        axis.text.x=element_text(angle=90,hjust = 1,vjust=0.5),
        axis.text.y=element_text(face = "bold", color = "grey40")) +
  scale_color_gradient(low="#F3F8B2",high="#35A355") + 
  #scale_fill_continuous() + 
  scale_y_discrete(position = "right") + 
  labs(x=NULL,y=NULL)
#ggsave("gsea_by_patient_figure/enriched_go_term_by_patient.pdf", width = 7.5, height = 9)
```



```{r,fig.width=7.5,fig.height=9}
pathway.df$ratio <- sapply(strsplit(pathway.df$GeneRatio, "/"), function(x){x[2]})
pathway.df$ratio <- as.numeric(pathway.df$ratio)
pathway.df$ratio <- pathway.df$Count / pathway.df$ratio

ggplot(pathway.df, aes(x = patient, y = Description)) + 
  geom_point(aes(size = ratio, color = scaled_log_qvalue)) + 
  theme_bw() +
  theme(panel.grid = element_blank(),
        axis.text.x=element_text(angle=90,hjust = 1,vjust=0.5),
        axis.text.y=element_text(face = "bold", color = "grey40")) +
  scale_color_gradient(low="#F3F8B2",high="#35A355") + 
  #scale_fill_continuous() + 
  scale_y_discrete(position = "right") + 
  labs(x=NULL,y=NULL)
```

#make qvalue heatmap
```{r,fig.width=6.5,fig.height=7}
hm_df <- pathway.df[, c("ID", "qvalue", "patient")]
hm_df$log_qvalue <- -log10(hm_df$qvalue)
hm_df$qvalue <- NULL

hm_df <- spread(hm_df, patient, log_qvalue)
#hm_df[is.na(hm_df)] <- 0
rownames(hm_df) <- hm_df$ID
hm_df$ID <- NULL
hm_df[hm_df > 10] = 10

pheatmap::pheatmap(hm_df[nrow(hm_df):1, ], cluster_cols = F, cluster_rows = F, na_col = "white", 
                   color = colorRampPalette(c("#F0C0C0", "firebrick3"))(50))
```

```{r,fig.width=6.5,fig.height=4}
hm_df <- hm_df[grepl("HALLMARK", rownames(hm_df)) | grepl("GOBP", rownames(hm_df)), ]
hm_df <- hm_df[!grepl("NFKB", rownames(hm_df)), ]
pheatmap::pheatmap(hm_df[nrow(hm_df):1, ], cluster_cols = F, cluster_rows = F, na_col = "white", 
                   color = colorRampPalette(c("#F0C0C0", "firebrick3"))(50))
```












































#end