---
title: "b_annotation"
author: "Hongke Peng"
date: "01/01/2022"
output: html_document
---

#load package
```{r}
library(dplyr)
library(Seurat)
library(ggplot2)
library(harmony)
```

#load data
```{r}
b=readRDS("b_cluster/b_refined.rds")
```

#maker gene
```{r,fig.width=2,fig.height=2}
DefaultAssay(b)="RNA"
FeaturePlot(b,reduction="wnn.umap",features="TCL1A",min.cutoff="q2",max.cutoff="q98",pt.size=0.02) + NoAxes() + NoLegend()
ggsave("b_annotation/featureplot_tcl1A.pdf",width=5,height=5)
```

```{r,fig.width=2,fig.height=2}
DefaultAssay(b)="RNA"
FeaturePlot(b,reduction="wnn.umap",features="TCL1A",min.cutoff="q2",max.cutoff="q98",pt.size=0.02) + NoAxes() + NoLegend()
ggsave("b_annotation/featureplot_tcl1A.pdf",width=5,height=5)
```

#refine clusters
```{r,fig.width=2.5,fig.height=2.5}
b$refine.type=as.character(b$wsnn_res.0.2)
b$refine.type[b$wsnn_res.0.2==3]=0
b$refine.type[b$wsnn_res.0.2==4]=3

c2=c("#4DBBD57F","#77B3D9","#D99ACE","#528DD9")
DimPlot(b,reduction="wnn.umap",group.by="refine.type",label=T,label.box=T,label.color="black",cols=c2)+NoLegend()+NoAxes() + ggtitle("B-cell subsets")
ggsave("b_annotation/dimplot_refine_cluster.pdf",width=5,height=5)
```

```{r,fig.width=5,fig.height=3}
memory.b=subset(b,refine.type%in%c(2,3))
memory.b$refine.type=paste("C",memory.b$refine.type,sep="")
plot.ls=list()
for (i in c("BCL2","BCL2A1","MCL1","BCL2L1")) {
  plot.ls[[i]]=VlnPlot(memory.b,features=i,group.by="refine.type",pt.size=0.01,cols=c("#D99ACE","#528DD9")) + xlab(NULL) + ylab(NULL) + NoLegend()
}
pdf("b_annotation/vlnplot_bcl2.pdf",width=10,height=10,)
gridExtra::grid.arrange(grobs=plot.ls,ncol=2)
dev.off()
```

```{r}
saveRDS(b,"b_annotation/b_refined.rds")
```

#de analysis
```{r}
pt=subset(b,refine.type %in% 0:2 & patient != "BC01007")
```


```{r,fig.width=3,fig.height=2.5}
library(SingleCellExperiment)
library(edgeR)
#make sce
matr=pt@assays$RNA@counts
md=pt@meta.data[,c("refine.type","patient","stage")]
#md$batch="batch1"
#md$batch[md$patient %in% c("BC01029_C25D1","BC01033_C1D1","BC01033_C23D1")]="batch2"
sce=SingleCellExperiment(assay=list(counts=matr),colData=md)
pool=scater::aggregateAcrossCells(sce,id=colData(sce)[,c("stage","patient")])

y=pool
y=DGEList(counts=counts(y),samples=colData(y),remove.zeros=T)
y$samples$stage=factor(y$samples$stage,levels=c("pre","post"))
  
#filtering 
keep=filterByExpr(y,group=y$samples$stage)
summary(keep)
y=y[keep, ,keep.lib.sizes=FALSE]
  
#calculate normalization factors
y=calcNormFactors(y)
  
# plot MDS
mds=plotMDS.DGEList(y,plot=F)
gg_df=data.frame(mds[c("x","y")],
                patient_id=y$samples$patient,
                group_id=y$samples$stage)

p1=ggplot(gg_df,aes(x,y,col=group_id,shape=patient_id))+
  geom_point(size=3)+
  labs(x="MDS dim.1",y="MDS dim2")+
  theme_bw()+
  theme(panel.grid.minor=element_blank())
p1
```

```{r}
#make design
f1=factor(y$samples$stage,levels=c("pre","post"))
f2=y$samples$patient
design=model.matrix(~0+f1+f2)
colnames(design)=gsub("f\\d","",colnames(design))
  
#make contrast
contr=makeContrasts(
  post_vs_pre=post-pre,
  levels=colnames(design)
)
  
y=estimateDisp(y,design)
plotBCV(y)
  
fit=glmFit(y,design)
lrt=glmLRT(fit,contrast=contr)
#fit <- glmQLFit(y,design)
#lrt <- glmQLFTest(fit,contrast=contr)
DEG=topTags(lrt,n=Inf)
  
#the proportion of cell express this gene
df=DEG$table
##pre percentage
pre.group=subset(pt,stage=="pre")
pre.group=pre.group@assays$RNA@counts
df$pre.perc=rowSums(pre.group[rownames(df),]>0)/ncol(pre.group)
##post persentage
post.group=subset(pt,stage=="post")
post.group=post.group@assays$RNA@counts
df$post.prct=rowSums(post.group[rownames(df),]>0)/ncol(post.group)
table(decideTests(lrt,p.value=0.05))
#save DGE list
#write.csv(df,file=paste0("../update_data/all_B_rv1007_de_list.csv"))
```

```{r,fig.width=5,fig.height=5}
#up=df[df$FDR<0.05&(df$post.prct>0.1 | df$pre.perc>0.1),]
up=df
volcano.lab=unlist(strsplit("S100A4/TRAF1/HMOX1/NEK6/PRDX4/LY96/CFLAR/TNIP2","/"))
EnhancedVolcano::EnhancedVolcano(df,
                x="logFC",y="FDR",
                lab=rownames(df),
                ylim=c(0,15),
                #xlim=c(-3,3),
                #title = paste(i,"volcano plot"),
                subtitle = paste0('FDR cutoff = 0.05', "  logFC cutoff = 0.5"),
                selectLab = volcano.lab,
                labSize = 3,
                legendPosition = 'top',
                legendLabSize = 12,
                legendIconSize = 4.0,
                drawConnectors = TRUE,
                #widthConnectors = 0.75,
                pCutoff = 0.05,
                FCcutoff = 0.5)
ggsave("b_annotation/volcanoplot.pdf",width=8,height=8)
```

```{r,fig.width=3,fig.height=3}
up=df[df$FDR<0.05&df$logFC>0&(df$post.prct>0.05),]
#go look pretty well
#library(clusterProfiler)
go.up=enrichGO(gene=rownames(up),
                OrgDb="org.Hs.eg.db",
                keyType="SYMBOL",
                ont="BP",
                pAdjustMethod="BH",
                pvalueCutoff=0.05,
                qvalueCutoff=0.05)
selected_go=filter(go.up,Count<=10)
selected_go=arrange(selected_go,desc(Count))
barplot(selected_go,showCategory=20)

ggplot(selected_go,aes(Count,fct_reorder(Description,Count)),showCategory=15) + 
    geom_col(orientation='y',fill="skyblue",width=0.6) + 
    theme_minimal() + 
    ylab(NULL) + 
    xlab("Gene counts") +
    NoLegend() + 
    theme(axis.text.y=element_text(face="bold")) + 
    ggtitle("selected GO terms")
```




```{r}
DimPlot(pt,reduction="wnn.umap")
```



















































end