---
title: "single cell de analysis"
author: "Hongke Peng"
date: "14/02/2022"
output: html_document
---
```{R}
library(dplyr)
library(Seurat)
library(ggplot2)
library(clusterProfiler)
```

#make umap for poster
```{r}
srt=readRDS("for_paper_data/srt_refine.rds")

#make mono cluster
srt$refind.type=0
#make cd4 t cluster
srt$refind.type[srt$wsnn_res.0.6==5]=1
srt$refind.type[srt$wsnn_res.0.6==6]=2
srt$refind.type[srt$wsnn_res.0.6==2]=3
srt$refind.type[srt$wsnn_res.0.6==1]=4
srt$refind.type[srt$wsnn_res.0.6==18]=5
srt$refind.type[srt$wsnn_res.0.6==16]=6
#make gd t cluster
srt$refind.type[srt$wsnn_res.0.6==15]=7
srt$refind.type[srt$wsnn_res.0.6==13]=8
srt$refind.type[srt$wsnn_res.0.6==10]=9
srt$refind.type[srt$wsnn_res.0.6%in%c(4,17,20)]=10
#leave cluster 11 for nk-T
#make b cluster
srt$refind.type[srt$wsnn_res.0.6==9]=12
srt$refind.type[srt$wsnn_res.0.6==3]=13
srt$refind.type[srt$wsnn_res.0.6==8]=14
srt$refind.type[srt$wsnn_res.0.6==14]=15
#make nk cluster
srt$refind.type[srt$wsnn_res.0.6==11]=16
srt$refind.type[srt$wsnn_res.0.6%in%c(0,19,24)]=17

#make nk-T cluster
nkt.name=colnames(srt)[srt$wsnn_res.1.2==32]
srt$refind.type[colnames(srt)%in%nkt.name]=11

colorset=c("darkgrey",#mono
           "#9BCA3C","#5FB14E","#91D1C2FF","#CADB73","#3B897C","#3BB846","#A5D0F0","#E882B4","#A56AAC","#DCBFDD","#F055A3",#t cluster
           "#4DBBD57F","#77B3D9","#D99ACE","#528DD9",#b cluster
           "#FF8F40","#FFAD73")
DimPlot(srt,reduction="wnn.umap",group.by="refind.type",cols=colorset,label=T,label.box=T,label.color="white",label.size=3.8) + ggtitle(NULL) + xlab("UMAP_1") + ylab("UMAP_2")
```
#part 1 B cluster -------------------
##find markers by MAST
```{r}
b=subset(srt,refind.type %in% c(12,13,14))
DefaultAssay(b)="RNA"
b.deg=FindMarkers(b,ident.1="post",ident.2="pre",group.by="stage",assay="RNA",test.use="MAST",logfc.threshold=0.25)
View(b.deg)
```

```{r,fig.width=10,fig.height=7}
df=b.deg
up=df[df$p_val_adj<0.05&df$avg_log2FC>0,]
#go look pretty well
go.up=enrichGO(gene=rownames(up),
               OrgDb="org.Hs.eg.db",
                keyType="SYMBOL",
                ont="ALL",
                pAdjustMethod="BH",
                pvalueCutoff=0.05,
                qvalueCutoff=0.05)

barplot(go.up,showCategory=50)
```
```{r,fig.width=20,fig.height=2}
de_list=rownames(df)[df$p_val_adj<0.05]
de_df=as.data.frame(t(b@assays$RNA@data[de_list,]))
#add meta information 
de_df$patient=b$patient
de_df$stage=b$stage

simple_func=function(x){mean(x,trim=0.01)}
hm_df=de_df %>% dplyr::group_by(patient,stage) %>% summarise_all(.funs=simple_func)
hm_df=rbind(hm_df[hm_df$stage=="post",],hm_df[hm_df$stage=="pre",])
hm_df=as.data.frame(hm_df)
rownames(hm_df)=paste(hm_df$patient,hm_df$stage,sep="_")

#make row annotation
row_anno=data.frame(stage=hm_df$stage,patient=hm_df$patient)
rownames(row_anno)=rownames(hm_df)

#make column annotation
col_anno=colnames(hm_df)
col_anno=b.deg[col_anno,]
col_anno$anno="up"
col_anno$anno[col_anno$avg_log2FC<0]="down"
col_anno=data.frame(direction=col_anno$anno)
rownames(col_anno)=colnames(hm_df)

hm_df=hm_df[,3:ncol(hm_df)]

#scale
hm_df=scale(hm_df)

pheatmap::pheatmap(hm_df,
                   annotation_row=row_anno,
                   annotation_col=col_anno,
                   cluster_rows=F,
                   cluster_cols=T,
                   treeheight_col=0,
                   treeheight_row=0,
                   #scale="column",
                   gaps_row=5)
```

```{r,fig.width=20,fig.height=2}
de_list=rownames(df)[df$p_val_adj<0.05]
de_df=as.data.frame(t(b@assays$RNA@data[de_list,]))
#add meta information 
de_df$patient=b$patient
de_df$stage=b$stage

simple_func=function(x){mean(x,trim=0.01)}
hm_df=de_df %>% dplyr::group_by(patient,stage) %>% summarise_all(.funs=simple_func)
#hm_df=rbind(hm_df[hm_df$stage=="post",],hm_df[hm_df$stage=="pre",])
hm_df=as.data.frame(hm_df)
rownames(hm_df)=paste(hm_df$patient,hm_df$stage,sep="_")

#make row annotation
row_anno=data.frame(stage=hm_df$stage,patient=hm_df$patient)
rownames(row_anno)=rownames(hm_df)

#make column annotation
col_anno=colnames(hm_df)
col_anno=b.deg[col_anno,]
col_anno$anno="up"
col_anno$anno[col_anno$avg_log2FC<0]="down"
col_anno=data.frame(direction=col_anno$anno)
rownames(col_anno)=colnames(hm_df)

hm_df=hm_df[,3:ncol(hm_df)]

#scale
hm_df=scale(hm_df)

pheatmap::pheatmap(hm_df,
                   annotation_row=row_anno,
                   annotation_col=col_anno,
                   cluster_rows=F,
                   cluster_cols=T,
                   treeheight_col=0,
                   treeheight_row=0,
                   #scale="column",
                   gaps_row=c(2,4,6,8))
```
```{r,fig.width=20,fig.height=2}
de_list=rownames(df)[df$p_val_adj<0.05]
de_df=as.data.frame(t(b@assays$RNA@data[de_list,]))
#add meta information 
de_df$patient=b$patient
de_df$stage=b$stage

simple_func=function(x){mean(x,trim=0.01)}
hm_df=de_df %>% dplyr::group_by(patient,stage) %>% summarise_all(.funs=simple_func)
#hm_df=rbind(hm_df[hm_df$stage=="post",],hm_df[hm_df$stage=="pre",])
hm_df=as.data.frame(hm_df)
rownames(hm_df)=paste(hm_df$patient,hm_df$stage,sep="_")
hm_df=hm_df[,-2]
hm_df
#calculate delta
delta_func=function(x){x[1]-x[2]}
hm_df_delta=hm_df %>% group_by(patient) %>% summarise_all(.funs=delta_func)
hm_df_delta=as.data.frame(hm_df_delta)
rownames(hm_df_delta)=hm_df_delta$patient
hm_df_delta=hm_df_delta[,-1]
#make column annotation
col_anno=colnames(hm_df_delta)
col_anno=b.deg[col_anno,]
col_anno$anno="up"
col_anno$anno[col_anno$avg_log2FC<0]="down"
col_anno=data.frame(direction=col_anno$anno)
rownames(col_anno)=colnames(hm_df_delta)

#set up cutoffs
num_vec=unlist(lapply(hm_df_delta, as.numeric))
g1=quantile(num_vec,0.01)
hm_df_delta[hm_df_delta<=g1]=g1
g2=quantile(num_vec,0.99)
hm_df_delta[hm_df_delta>=g2]=g2

paletteLength <- 50
myColor=colorRampPalette(c("#4575B4", "white","#D73027"))(paletteLength)

# length(breaks) == length(paletteLength) + 1
# use floor and ceiling to deal with even/odd length pallettelengths
myBreaks <- c(seq(min(hm_df_delta), 0, length.out=ceiling(paletteLength/2) + 1), 
              seq(max(hm_df_delta)/paletteLength, max(hm_df_delta), length.out=floor(paletteLength/2)))

pheatmap::pheatmap(hm_df_delta,
                   annotation_col=col_anno,
                   cluster_rows=F,
                   cluster_cols=T,
                   show_colnames=T,
                   border_color="white",
                   treeheight_col=0,
                   treeheight_row=0,
                   #scale="row",
                   color=myColor,
                   breaks=myBreaks,
                   clustering_distance_cols="canberra",
                   fontsize_row=10,
                   fontsize_col=3,
                   filename="make_figures_for_paper_folder/hm_de_MAST.pdf",
                   width=20,height=2)
```
##find markers one by one
```{r,fig.width=20,fig.height=4}
b=subset(srt,refind.type %in% c(12,13,14))
DefaultAssay(b)="RNA"

de_table_list=list()
#de for each patient
for (i in unique(b$patient)) {
  x=subset(b,patient==i)
  de_table=FindMarkers(x,ident.1="post",ident.2="pre",group.by="stage",assay="RNA",test.use="MAST",logfc.threshold=0.25)
  de_table$gene=rownames(de_table)
  de_table=de_table[de_table$p_val_adj<0.05,c(6,2)]
  colnames(de_table)=c("gene",i)
  de_table_list[[i]]=de_table
}

#merge de tables by genes
de_table_merge=de_table_list[[1]]
for (i in 2:length(de_table_list)) {
  de_table_merge=merge(de_table_merge,de_table_list[[i]],by="gene",all=T)
}

rownames(de_table_merge)=de_table_merge$gene
de_table_merge=de_table_merge[,2:ncol(de_table_merge)]

de_table_merge[is.na(de_table_merge)]=0

pheatmap::pheatmap(t(de_table_merge),
                   #annotation_col=col_anno,
                   cluster_rows=T,
                   cluster_cols=T,
                   show_colnames=T,
                   border_color="white",
                   treeheight_col=0,
                   treeheight_row=0,
                   #scale="row",
                   color=myColor,
                   breaks=myBreaks,
                   clustering_distance_cols="canberra",
                   fontsize_row=10,
                   fontsize_col=8
                   #filename="make_figures_for_paper_folder/hm_t1_de_MAST.pdf",
                   #width=8,height=2
                   )
```

#overall de + p_value 
```{r,fig.width=30,fig.height=3}
b=subset(srt,refind.type %in% c(12,13,14))
DefaultAssay(b)="RNA"
b.deg=FindMarkers(b,ident.1="post",ident.2="pre",group.by="stage",assay="RNA",test.use="MAST",logfc.threshold=0.25)

de_table_list=list()
#de for each patient
for (i in unique(b$patient)) {
  x=subset(b,patient==i)
  de_table=FindMarkers(x,ident.1="post",ident.2="pre",group.by="stage",assay="RNA",test.use="wilcox",logfc.threshold=0.05)
  de_table$gene=rownames(de_table)
  de_table=de_table[de_table$p_val_adj<0.05&(de_table$gene%in%rownames(b.deg)),c(6,2)]
  colnames(de_table)=c("gene",i)
  de_table_list[[i]]=de_table
}

#merge de tables by genes
de_table_merge=data.frame(gene=rownames(b.deg))
for (i in 1:length(de_table_list)) {
  de_table_merge=merge(de_table_merge,de_table_list[[i]],by="gene",all=T)
}

rownames(de_table_merge)=de_table_merge$gene
de_table_merge=de_table_merge[,2:ncol(de_table_merge)]
de_table_merge=de_table_merge[rowSums(is.na(de_table_merge))<4,]
de_table_merge[is.na(de_table_merge)]=0
de_table_merge=t(de_table_merge)

#set up cutoffs
num_vec=unlist(lapply(de_table_merge, as.numeric))
g1=quantile(num_vec,0.02)
de_table_merge[de_table_merge<=g1]=g1
g2=quantile(num_vec,0.98)
de_table_merge[de_table_merge>=g2]=g2

paletteLength <- 50
myColor=colorRampPalette(c("#4575B4", "white","#D73027"))(paletteLength)

# length(breaks) == length(paletteLength) + 1
# use floor and ceiling to deal with even/odd length pallettelengths
myBreaks <- c(seq(min(de_table_merge), 0, length.out=ceiling(paletteLength/2) + 1), 
              seq(max(de_table_merge)/paletteLength, max(de_table_merge), length.out=floor(paletteLength/2)))

#make column annotation
col_anno=colnames(de_table_merge)
col_anno=b.deg[col_anno,]
col_anno$anno="up"
col_anno$anno[col_anno$avg_log2FC<0]="down"
col_anno=data.frame(direction=col_anno$anno)
rownames(col_anno)=colnames(de_table_merge)

a=pheatmap::pheatmap(de_table_merge,
                   annotation_col=col_anno,
                   cluster_rows=F,
                   cluster_cols=T,
                   show_colnames=T,
                   border_color="white",
                   treeheight_col=0,
                   treeheight_row=0,
                   #scale="row",
                   color=myColor,
                   breaks=myBreaks,
                   clustering_distance_cols="euclidean",
                   fontsize_row=10,
                   fontsize_col=6,
                   filename="make_figures_for_paper_folder/hm_t1_de_MAST_pvalue.pdf",
                   width=30,height=3
                   )

```



#part 2 CD4 t cluster
```{r}
t1=subset(srt,refind.type==1)
DefaultAssay(t1)="RNA"
t1.deg=FindMarkers(t1,ident.1="post",ident.2="pre",group.by="stage",assay="RNA",test.use="MAST",logfc.threshold=0.25)
View(t1.deg)
```

```{r,fig.width=10,fig.height=7}
df=t1.deg
up=df[df$p_val_adj<0.05&df$avg_log2FC>0,]
#go look pretty well
go.up=enrichGO(gene=rownames(up),
               OrgDb="org.Hs.eg.db",
                keyType="SYMBOL",
                ont="ALL",
                pAdjustMethod="BH",
                pvalueCutoff=0.05,
                qvalueCutoff=0.05)

barplot(go.up,showCategory=50)
```
```{r,fig.width=20,fig.height=2}
de_list=rownames(df)[df$p_val_adj<0.05]
de_df=as.data.frame(t(t1@assays$RNA@data[de_list,]))
#add meta information 
de_df$patient=t1$patient
de_df$stage=t1$stage

simple_func=function(x){mean(x,trim=0.01)}
hm_df=de_df %>% dplyr::group_by(patient,stage) %>% summarise_all(.funs=simple_func)
#hm_df=rbind(hm_df[hm_df$stage=="post",],hm_df[hm_df$stage=="pre",])
hm_df=as.data.frame(hm_df)
rownames(hm_df)=paste(hm_df$patient,hm_df$stage,sep="_")
hm_df=hm_df[,-2]
hm_df
#calculate delta
delta_func=function(x){x[1]-x[2]}
hm_df_delta=hm_df %>% group_by(patient) %>% summarise_all(.funs=delta_func)
hm_df_delta=as.data.frame(hm_df_delta)
rownames(hm_df_delta)=hm_df_delta$patient
hm_df_delta=hm_df_delta[,-1]
#make column annotation
col_anno=colnames(hm_df_delta)
col_anno=t1.deg[col_anno,]
col_anno$anno="up"
col_anno$anno[col_anno$avg_log2FC<0]="down"
col_anno=data.frame(direction=col_anno$anno)
rownames(col_anno)=colnames(hm_df_delta)

#set up cutoffs
num_vec=unlist(lapply(hm_df_delta, as.numeric))
g1=quantile(num_vec,0.01)
hm_df_delta[hm_df_delta<=g1]=g1
g2=quantile(num_vec,0.99)
hm_df_delta[hm_df_delta>=g2]=g2

paletteLength <- 50
myColor=colorRampPalette(c("#4575B4", "white","#D73027"))(paletteLength)

# length(breaks) == length(paletteLength) + 1
# use floor and ceiling to deal with even/odd length pallettelengths
myBreaks <- c(seq(min(hm_df_delta), 0, length.out=ceiling(paletteLength/2) + 1), 
              seq(max(hm_df_delta)/paletteLength, max(hm_df_delta), length.out=floor(paletteLength/2)))

hm_df_delta=hm_df_delta[,c(rownames(t1.deg)[t1.deg$avg_log2FC>0],rownames(t1.deg)[t1.deg$avg_log2FC<0])]

a=pheatmap::pheatmap(hm_df_delta,
                   annotation_col=col_anno,
                   cluster_rows=F,
                   cluster_cols=F,
                   show_colnames=T,
                   border_color="white",
                   treeheight_col=0,
                   treeheight_row=0,
                   #scale="row",
                   color=myColor,
                   breaks=myBreaks,
                   clustering_distance_cols="canberra",
                   fontsize_row=10,
                   fontsize_col=8,
                   filename="make_figures_for_paper_folder/hm_t1_de_MAST.pdf",
                   width=8,height=2)
```

#part 3 make loop for all cluster
```{r,fig.width=20,fig.height=3}
simple_func=function(x){mean(x,trim=0.01)}
delta_func=function(x){x[1]-x[2]}
hm_list=list()

for (i in c(1:10,16,17)) {
  #find de genes
  x=subset(srt,refind.type==i)
  DefaultAssay(x)="RNA"
  deg=FindMarkers(x,ident.1="post",ident.2="pre",group.by="stage",assay="RNA",test.use="MAST",logfc.threshold=0.25)
  
  de_list=rownames(deg)[deg$p_val_adj<0.05]
  de_df=as.data.frame(t(x@assays$RNA@data[de_list,]))
  #add meta information 
  de_df$patient=x$patient
  de_df$stage=x$stage
  
  hm_df=de_df %>% dplyr::group_by(patient,stage) %>% summarise_all(.funs=simple_func)
  hm_df=as.data.frame(hm_df)
  rownames(hm_df)=paste(hm_df$patient,hm_df$stage,sep="_")
  hm_df=hm_df[,-2]
  #calculate delta
  hm_df_delta=hm_df %>% group_by(patient) %>% summarise_all(.funs=delta_func)
  hm_df_delta=as.data.frame(hm_df_delta)
  rownames(hm_df_delta)=hm_df_delta$patient
  hm_df_delta=hm_df_delta[,-1]
  #make column annotation
  col_anno=colnames(hm_df_delta)
  col_anno=deg[col_anno,]
  col_anno$anno="up"
  col_anno$anno[col_anno$avg_log2FC<0]="down"
  col_anno=data.frame(direction=col_anno$anno)
  rownames(col_anno)=colnames(hm_df_delta)

  #set up cutoffs
  num_vec=unlist(lapply(hm_df_delta, as.numeric))
  g1=quantile(num_vec,0.01)
  hm_df_delta[hm_df_delta<=g1]=g1
  g2=quantile(num_vec,0.99)
  hm_df_delta[hm_df_delta>=g2]=g2

  paletteLength <- 50
  myColor=colorRampPalette(c("#4575B4", "white","#D73027"))(paletteLength)
  
  myBreaks <- c(seq(min(hm_df_delta), 0, length.out=ceiling(paletteLength/2) + 1), 
              seq(max(hm_df_delta)/paletteLength, max(hm_df_delta), length.out=floor(paletteLength/2)))
  
  hm_df_delta=hm_df_delta[,c(rownames(deg)[deg$avg_log2FC>0&deg$p_val_adj<0.05],rownames(deg)[deg$avg_log2FC<0&deg$p_val_adj<0.05])]

  a=pheatmap::pheatmap(hm_df_delta,
                   annotation_col=col_anno,
                   cluster_rows=F,
                   cluster_cols=T,
                   show_colnames=T,
                   border_color="white",
                   treeheight_col=0,
                   treeheight_row=0,
                   #scale="row",
                   color=myColor,
                   breaks=myBreaks,
                   clustering_distance_cols="euclidean",
                   fontsize_row=10,
                   fontsize_col=3,
                   #filename=paste0("make_figures_for_paper_folder/hm_C",i,"_de_MAST.pdf"),
                   width=20,height=2)
  up.gene=rownames(deg)[deg$p_val_adj<0.05&deg$avg_log2FC>0]
  down.gene=rownames(deg)[deg$p_val_adj<0.05&deg$avg_log2FC<0]
  
  refined_df=hm_df_delta[,a$tree_col$order]
  gene_order=c(colnames(refined_df)[colnames(refined_df) %in% down.gene],colnames(refined_df)[colnames(refined_df) %in% up.gene])
  refined_df=hm_df_delta[,gene_order]
  
  fig_width=(length(de_list)/354)*15 + 2.5
  
  pheatmap::pheatmap(refined_df,
                   annotation_col=col_anno,
                   cluster_rows=F,
                   cluster_cols=F,
                   show_colnames=T,
                   border_color="white",
                   treeheight_col=0,
                   treeheight_row=0,
                   #scale="row",
                   color=myColor,
                   breaks=myBreaks,
                   fontsize_row=10,
                   fontsize_col=3,
                   filename=paste0("make_figures_for_paper_folder/hm_C",i,"_de_MAST.pdf"),
                   main=paste0("Expr changes in each pt, C", i),
                   width=fig_width,
                   height=2)
}
```








#end