---
title: "to reviewer"
author: "Hongke Peng"
date: '2022-05-31'
output: html_document
---

#load packages
```{R}
library(dplyr)
library(Seurat)
library(ggplot2)
library(ggsci)
library(SingleCellExperiment)
library(edgeR)
```

#load in data
```{r}
srt = readRDS("for_paper_data/srt_refine.rds")
```

#make re-find clusters
```{r,fig.width=5,fig.height=5}
#make mono cluster
srt$refind.type=0
#make cd4 t cluster
srt$refind.type[srt$wsnn_res.0.6==5]=1
srt$refind.type[srt$wsnn_res.0.6==6]=2
srt$refind.type[srt$wsnn_res.0.6==2]=3
srt$refind.type[srt$wsnn_res.0.6==1]=4
srt$refind.type[srt$wsnn_res.0.6==18]=5
srt$refind.type[srt$wsnn_res.0.6==16]=6
#make gd t cluster
srt$refind.type[srt$wsnn_res.0.6==15]=7
srt$refind.type[srt$wsnn_res.0.6==13]=8
srt$refind.type[srt$wsnn_res.0.6==10]=9
srt$refind.type[srt$wsnn_res.0.6%in%c(4,17,20)]=10
#leave cluster 11 for nk-T
#make b cluster
srt$refind.type[srt$wsnn_res.0.6==9]=12
srt$refind.type[srt$wsnn_res.0.6==3]=13
srt$refind.type[srt$wsnn_res.0.6==8]=14
srt$refind.type[srt$wsnn_res.0.6==14]=15
#make nk cluster
srt$refind.type[srt$wsnn_res.0.6==11]=16
srt$refind.type[srt$wsnn_res.0.6%in%c(0,19,24)]=17

#make nk-T cluster
DimPlot(srt,reduction="wnn.umap",group.by="wsnn_res.1.2",label=T) + ggtitle(NULL) + xlab("UMAP_1") + ylab("UMAP_2")
nkt.name=colnames(srt)[srt$wsnn_res.1.2==32]
srt$refind.type[colnames(srt)%in%nkt.name]=11
```
# overall umap
```{r,fig.width=5,fig.height=5}
colorset=c("darkgrey",#mono
           "#9BCA3C","#5FB14E","#91D1C2FF","#CADB73","#3B897C","#3BB846","#A5D0F0","#E882B4","#A56AAC","#DCBFDD","#F055A3",#t cluster
           "#4DBBD57F","#77B3D9","#D99ACE","#528DD9",#b cluster
           "#FF8F40","#FFAD73")
DimPlot(srt,reduction="wnn.umap",group.by="refind.type",cols=colorset,label=T,label.box=T,label.color="white",label.size=3.8,raster=T) + 
  theme_bw() +
  theme(panel.grid.major=element_blank(),panel.grid.minor=element_blank(),axis.title=element_text(size=30)) +
  NoLegend() +
  ggtitle(NULL) + 
  xlab("umap 1") + 
  ylab("umap 2")
```

#b cell adt
```{r,fig.width=50,fig.width=50}
b=subset(srt, refind.type %in% 12:15)
adt = rownames(b)
VlnPlot(b, features = adt, group.by = "refind.type", cols = c("#4DBBD57F","#77B3D9","#D99ACE","#528DD9"), pt.size = 0, ncol = 11)
```

##origin
```{r,fig.width=6,fig.height=5}
DefaultAssay(b)="DSB"
rownames(b)[grep("HLA",rownames(b))]
prot_to_use=c("CD45RA","CD29","CD73-(Ecto-5-nucleotidase)","CD20","HLA-A-B-C","HLA-DR","CD62L","CD32","CD35","CD11c","CD95-(Fas)","CD69.1",
              "CD21","integrin-B7","CD48.1","CD27.1","CD38.1","CD19.1","CD185-(CXCR5)","CD24.1")
DotPlot(b,assay="DSB",features=prot_to_use,cols="Spectral",group.by="refind.type") + coord_flip()

prot_to_use=c("CD45RA","CD29","CD73-(Ecto-5-nucleotidase)","CD20","HLA-A-B-C","CD62L","CD32","CD35","CD11c","CD95-(Fas)","CD69","CD21",
              "integrin-B7","CD48","CD27","CD38","CD19","CD185-(CXCR5)","CD24")
DotPlot(b,assay="ADT",features=prot_to_use,cols="Spectral",group.by="refind.type") + coord_flip()
```

##baseline: Ctrls
```{r,fig.width=5.5,fig.height=4.5}
dsb_mtx=GetAssayData(b,assay="DSB",slot="data")
dsb_mtx[1:3,1:3]
dsb_to_use=c("CD45RA","CD29","CD73-(Ecto-5-nucleotidase)","CD20","HLA-A-B-C","HLA-DR","CD62L","CD32","CD35","CD11c","CD95-(Fas)","CD69.1",
             "CD21","integrin-B7","CD48.1","CD27.1","CD38.1","CD19.1","CD185-(CXCR5)","CD24.1")
dsb_mtx_seleted=dsb_mtx[dsb_to_use,]
ctrl_mtx=dsb_mtx[grep("Ctrl",rownames(dsb_mtx)),]
ctrl_mtx=colSums(ctrl_mtx)/4
gate = mean(ctrl_mtx) #+ sd(ctrl_mtx)

dsb_mtx_seleted=dsb_mtx_seleted-gate
dsb_mtx_seleted[dsb_mtx_seleted<0]=0
dsb_mtx_seleted[,1:3]

b[["selected_dsb"]]=CreateAssayObject(data = dsb_mtx_seleted)
DefaultAssay(b)="selected_dsb"
b=ScaleData(b)
DotPlot(b,assay="selected_dsb",features=rownames(b),group.by="refind.type",cols=c("#FAF9D8","#243577"),cluster.idents=T) + coord_flip()
```

```{r,fig.width=5.5,fig.height=4.5}
dsb_mtx=GetAssayData(b,assay="ADT",slot="data")
dsb_mtx[1:3,1:3]
dsb_to_use=c("CD45RA","CD29","CD73-(Ecto-5-nucleotidase)","CD20","HLA-A-B-C","CD62L","CD32","CD35","CD11c","CD95-(Fas)","CD69","CD21",
              "integrin-B7","CD48","CD27","CD38","CD19","CD185-(CXCR5)","CD24")
dsb_mtx_seleted=dsb_mtx[dsb_to_use,]
ctrl_mtx=dsb_mtx[grep("Ctrl",rownames(dsb_mtx)),]
ctrl_mtx=colSums(ctrl_mtx)/4
gate = mean(ctrl_mtx) #+ sd(ctrl_mtx)

dsb_mtx_seleted=dsb_mtx_seleted-gate
dsb_mtx_seleted[dsb_mtx_seleted<0]=0
dsb_mtx_seleted[,1:3]

b[["selected_adt"]]=CreateAssayObject(data = dsb_mtx_seleted)
DefaultAssay(b)="selected_adt"
b=ScaleData(b)
DotPlot(b,assay="selected_adt",features=rownames(b),group.by="refind.type",cols=c("#FAF9D8","#243577"),cluster.idents = T) + coord_flip()
```
##order the prot
```{r,fig.width=5.5,fig.height=4.5}
dsb_mtx=GetAssayData(b,assay="ADT",slot="data")
dsb_mtx[1:3,1:3]
#dsb_to_use=c("CD45RA","CD29","CD73-(Ecto-5-nucleotidase)","CD20","HLA-A-B-C","CD62L","CD32","CD35","CD11c","CD95-(Fas)","CD69","CD21",
#              "integrin-B7","CD48","CD27","CD38","CD19","CD185-(CXCR5)","CD24")

dsb_to_use=c("CD62L","CD38","CD69","integrin-B7","CD185-(CXCR5)","CD24","CD35","CD73-(Ecto-5-nucleotidase)","CD21",
             "CD32","HLA-A-B-C","CD20","CD45RA","CD19","CD48","CD11c","CD95-(Fas)","CD29","CD27")

dsb_mtx_seleted=dsb_mtx[dsb_to_use,]
ctrl_mtx=dsb_mtx[grep("Ctrl",rownames(dsb_mtx)),]
ctrl_mtx=colSums(ctrl_mtx)/4
gate = mean(ctrl_mtx) #+ sd(ctrl_mtx)

dsb_mtx_seleted=dsb_mtx_seleted-gate
dsb_mtx_seleted[dsb_mtx_seleted<0]=0
dsb_mtx_seleted[,1:3]

b[["selected_adt"]]=CreateAssayObject(data = dsb_mtx_seleted)
DefaultAssay(b)="selected_adt"
b=ScaleData(b)
DotPlot(b,assay="selected_adt",features=rownames(b),group.by="refind.type",cols=c("#FAF9D8","#243577"),cluster.idents = F) + coord_flip() + 
  ylab("B-cell clusters") + xlab(NULL)
ggsave("to_reviewers/b_cell_markers.pdf",width=5.5,height=4.5)
```


# DEGs between B-cell cluster
## make dotplot
```{r,fig.width=7,fig.height=10}
deg=read.csv("de_list/b_cell.csv")
deg=deg[deg$FDR<0.05,]
deg=deg[deg$post.prct>0.1|deg$pre.perc>0.1,]
up=deg[deg$logFC>0,]
up$pre_post_prc=up$pre.perc
up$pre.perc[up$post.prct>up$pre.perc]=up$post.prct[up$post.prct>up$pre.perc]
up=up[order(up$pre_post_prc,decreasing = F),]

down=deg[deg$logFC<0,]
down$pre_post_prc=down$pre.perc
down$pre.perc[down$post.prct>down$pre.perc]=down$post.prct[down$post.prct>down$pre.perc]
down=down[order(down$pre_post_prc,decreasing = F),]

select_b=subset(b,refind.type%in%c(12,13,14))
select_b$stage=factor(select_b$stage, levels = c("pre","post"))

plot_degs=c(up$X,down$X)

DotPlot(select_b, assay = "RNA", features = plot_degs, cols = "Spectral", group.by = "stage", split.by = "patient") + coord_flip() + 
  ylab(NULL) + 
  xlab(NULL) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))

#ggsave("to_reviewers/deg_list.pdf",width = 4, height = 10)
```

## make heatmap
## b cell cluster
```{r, fig.width=5, fig.height=10}
table(select_b$patient)
table(select_b$stage)
select_b$category <- paste(select_b$stage, select_b$patient, sep = "_")
table(select_b$category)
av <- AverageExpression(select_b, assays = "RNA", group.by = "category")
av <- av$RNA

deg=read.csv("de_list/b_cell.csv")
deg=deg[deg$FDR<0.05,]
#deg=deg[deg$post.prct>0.1|deg$pre.perc>0.1,]
all.deg <- av[deg$X, ]
#all.deg <- t(scale(t(all.deg)))
anno <- data.frame(stage = colnames(all.deg))
rownames(anno) <- anno$stage
anno$stage <- sapply(strsplit(anno$stage, "_"), function(x){x[1]})
anno$stage <- factor(anno$stage, levels = c("pre", "post"))

make_order <- c(colnames(all.deg)[c(6:10, 1:5)])
pheatmap::pheatmap(all.deg[, make_order], scale = "row", cluster_cols = F, fontsize_row = 5, treeheight_row = 0, annotation_col = anno, main = "DEG in B-cell cluster 12, 13, 14", cellwidth = 25, cellheight = 5,
                   filename = "to_reviewers/hm_deg_b_cluster.pdf", width = 6, height = 10
                   )
```

```{r, fig.width=5, fig.height=10}
table(select_b$patient)
table(select_b$stage)
select_b$category <- paste(select_b$stage, select_b$patient, sep = "_")
table(select_b$category)
av <- AverageExpression(select_b, assays = "RNA", group.by = "category")
av <- av$RNA

deg=read.csv("de_list/b_cell.csv")
deg=deg[deg$FDR<0.05,]
deg=deg[deg$post.prct>0.05|deg$pre.perc>0.05,]
all.deg <- av[deg$X, ]
#all.deg <- t(scale(t(all.deg)))
anno <- data.frame(stage = colnames(all.deg))
rownames(anno) <- anno$stage
anno$stage <- sapply(strsplit(anno$stage, "_"), function(x){x[1]})
anno$stage <- factor(anno$stage, levels = c("pre", "post"))

make_order <- c(colnames(all.deg)[c(6:10, 1:5)])
pheatmap::pheatmap(all.deg[, make_order], scale = "row", cluster_cols = F, fontsize_row = 5, treeheight_row = 0, annotation_col = anno, main = "DEG (expressed in > 5% cells) in B-cell cluster 12, 13, 14", cellwidth = 25, cellheight = 5,
                   filename = "to_reviewers/hm_deg_b_cluster_filtered.pdf", width = 6, height = 10
                   )
```

## other subsets
```{r, fig.width=5, fig.height=10}
for(i in c(1:3, 6:10, 16, 17)) {
  x <- subset(srt, refind.type == i)
  table(x$patient)
  table(x$stage)
  x$category <- paste(x$stage, x$patient, sep = "_")
  table(x$category)
  
  av <- AverageExpression(x, assays = "RNA", group.by = "category")
  av <- av$RNA
  if (i <= 10) {
    deg <- read.csv(paste0("de_list/t_", i, ".csv"))
  } else {
    deg <- read.csv(paste0("de_list/nk_", i, ".csv"))
  }
  deg=deg[deg$FDR<0.05,]
  deg=deg[deg$post.prct>0.05|deg$pre.perc>0.05,]
  if (nrow(deg) == 0) {next}
  all.deg <- av[deg$X, ]
  
  anno <- data.frame(stage = colnames(av))
  rownames(anno) <- anno$stage
  anno$stage <- sapply(strsplit(anno$stage, "_"), function(x){x[1]})
  anno$stage <- factor(anno$stage, levels = c("pre", "post"))
  
  if (i <= 10) {
    hm_name <- paste("DEGs in t-cell cluster", i, sep = " ")
  } else {
    hm_name <- paste("DEGs in nk-cell cluster", i, sep = " ")
  }
  pheatmap::pheatmap(all.deg[, make_order], scale = "row", cluster_cols = F, fontsize_row = 5, treeheight_row = 0, annotation_col = anno, main = hm_name, cellwidth = 25, cellheight = 5,
                     filename = paste0("to_reviewers/hm_deg_", i, "_cluster.pdf"), width = 6, height = 10
                     )
}
```


## for cluster 5
```{r}
x <- subset(srt, refind.type == 5)
table(x$patient)
table(x$stage)
x$category <- paste(x$stage, x$patient, sep = "_")
table(x$category)
  
av <- AverageExpression(x, assays = "RNA", group.by = "category")
av <- av$RNA

deg <- read.csv("de_list/t_5.csv")
deg=deg[deg$FDR<0.05,]
deg=deg[deg$post.prct>0.05|deg$pre.perc>0.05,]
all.deg <- av[deg$X, ]

df <- data.frame(GNLY = all.deg[c(6:10, 1:5)])
df <- t(df)

anno <- data.frame(stage = colnames(av))
rownames(anno) <- anno$stage
anno$stage <- sapply(strsplit(anno$stage, "_"), function(x){x[1]})
anno$stage <- factor(anno$stage, levels = c("pre", "post"))
  
pheatmap::pheatmap(df, scale = "row", cluster_cols = F, cluster_rows = F, fontsize_row = 5, treeheight_row = 0, annotation_col = anno, main = "DEGs in t-cell cluster 5", cellwidth = 25, cellheight = 5,
                   filename = paste0("to_reviewers/hm_deg_5_cluster.pdf"), width = 6, height = 10
                     )
```

## for cluster 4
```{r}
x <- subset(srt, refind.type == 4)
table(x$patient)
table(x$stage)
x$category <- paste(x$stage, x$patient, sep = "_")
table(x$category)
  
av <- AverageExpression(x, assays = "RNA", group.by = "category")
av <- av$RNA

deg <- read.csv("de_list/t_4.csv")
deg=deg[deg$FDR<0.05,]
deg=deg[deg$post.prct>0.05|deg$pre.perc>0.05,]
all.deg <- av[deg$X, ]

df <- data.frame(HSPA1B = all.deg[c(6:10, 1:5)])
df <- t(df)

anno <- data.frame(stage = colnames(av))
rownames(anno) <- anno$stage
anno$stage <- sapply(strsplit(anno$stage, "_"), function(x){x[1]})
anno$stage <- factor(anno$stage, levels = c("pre", "post"))
  
pheatmap::pheatmap(df, scale = "row", cluster_cols = F, cluster_rows = F, fontsize_row = 5, treeheight_row = 0, annotation_col = anno, main = "DEGs in t-cell cluster 4", cellwidth = 25, cellheight = 5,
                   filename = paste0("to_reviewers/hm_deg_4_cluster.pdf"), width = 6, height = 10
                     )
```


#t cell composition
```{r, fig.width=7, fig.height=7}
t <- subset(srt, refind.type %in% 1:10)
t$category <- paste(t$stage, t$patient, sep = "_")
df <- table(t$category, t$refind.type)/rowSums(table(t$category, t$refind.type))
df <- as.data.frame(df)
colnames(df) <- c("category", "cluster", "fraction")
df$stage <- sapply(strsplit(as.character(df$category), "_"), function(x) {x[1]})
df$patient <- sapply(strsplit(as.character(df$category), "_"), function(x) {x[2]})
df$stage <- factor(df$stage, levels = c("pre", "post"))

ggplot(df, aes(x = stage, y = fraction)) + geom_line(aes(group = patient), linetype="dashed", col="skyblue") + geom_point() + facet_wrap(~cluster) + theme_bw()
ggsave("to_reviewers/composition_changes.pdf", width = 7, height = 7)
```


# umap split by patient and stage
```{r, fig.width=10, fig.height=25}
srt$category <- paste(srt$stage, srt$patient, sep = "_")
table(srt$category)
cate_order <- unique(srt$category)

srt$category <- factor(srt$category, levels = cate_order)
DimPlot(srt,reduction="wnn.umap",group.by="refind.type",split.by = "category",cols=colorset,label=T,label.box=F,label.size=7,raster=T,ncol = 2)
ggsave("to_reviewers/umap_split_by_pt_stage.pdf", width = 10, height = 25)
```






```{r}
for(i in c(1:10, 16, 17)) {
  if (i <= 10) {
    deg <- read.csv(paste0("de_list/t_", i, ".csv"))
  } else {
    deg <- read.csv(paste0("de_list/nk_", i, ".csv"))
  }
  deg=deg[deg$FDR<0.05,]
  print(deg)
}
```

```{r, fig.width=16, fig.height=12}
plot.ls <- list()
for (i in unique(srt$category)) {
  x <- subset(srt, category == i)
  plot.ls[[i]] <- DimPlot(x,reduction="wnn.umap",group.by="refind.type",cols=colorset,label=T,label.box=F,label.size=5,raster=T) + NoLegend() + NoAxes() + ggtitle(NULL)
}
gridExtra::grid.arrange(grobs=plot.ls,ncol=4)
```

































#end